### ISSUE TITLE
Failed on negatives

### ISSUE THREAD

**Issue by tulipper** [kevinlewi/fhipe#1]
Hello !
I use fhipe to calculate the inner products of vectors, and it works pretty well if the product is positive. 
but when the expected inner product is negative, it cann't find the correct result.

Could you give me some threads on using it to calculate the nenative product?
Thank you very much!

**Comment by kevinlewi** [comment]
Hi @tulipper (sorry for the super-late reply)! In case you're still facing this issue -- no, I would calculations where the expected inner product is negative. Instead, I would try scaling the inputs in a way so that the inner product can never be negative. Hope that helps!

**Comment by kevinlewi** [comment]
(Closing the issue but feel free to reopen if there is followup)
