### ISSUE TITLE
Maximum length vector that can be encrypted.

### ISSUE THREAD

**Issue by LittleDonkey7** [kevinlewi/fhipe#2]
I would like to ask you what is the maximum length of vector that can be calculated.  I tried to generate encryption parameters for a vector of length 1000, but it took too long. Is it theoretically possible to generate encryption parameters of this order of magnitude, and in practice?

**Comment by kevinlewi** [comment]
That's a good question. In theory, nothing should prevent the generation of encryption parameters for a vector of length 1000, though the experiments we ran were for vectors of length 50.

**Comment by kevinlewi** [comment]
(Closing this issue but feel free to re-open if there is followup)
